name: Run Playwright Tests and Email Report

on:
  push:
    branches: [ maisfgghtrwern1 ]
  schedule:
    - cron: '20 20 * * *'  # 2:00 AM IST (UTC+5:30)

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      report_date: ${{ steps.get_date.outputs.report_date }}
      total: ${{ steps.summary.outputs.total }}
      passed: ${{ steps.summary.outputs.passed }}
      failed: ${{ steps.summary.outputs.failed }}
      skipped: ${{ steps.summary.outputs.skipped }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Get report date
        id: get_date
        run: echo "report_date=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Run Playwright Tests
        env:
          URL_ADMIN: https://stg.chat.bluedropacademy.com/admin
          URL_CHATBOT: https://bluedropacademy.wixsite.com/website-1/chat6?rc=test-site
        run: |
          rm -rf playwright-report site
          npx playwright test --project=chromium --workers=1 --reporter=json,test-results.json,html

      - name: Extract test summary
        id: summary
        run: |
          [ ! -f "test-results.json" ] && echo "Report not found!" && exit 1
          echo "total=$(jq '.suites | map(.specs | length) | add' test-results.json)" >> $GITHUB_OUTPUT
          echo "passed=$(jq '[.. | .status? | select(. == "passed")] | length' test-results.json)" >> $GITHUB_OUTPUT
          echo "failed=$(jq '[.. | .status? | select(. == "failed")] | length' test-results.json)" >> $GITHUB_OUTPUT
          echo "skipped=$(jq '[.. | .status? | select(. == "skipped")] | length' test-results.json)" >> $GITHUB_OUTPUT

      - name: Prepare report for Pages
        run: |
          mkdir -p site/staging-report-${{ steps.get_date.outputs.report_date }}
          mv playwright-report/* site/staging-report-${{ steps.get_date.outputs.report_date }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    outputs:
      page_url: ${{ steps.deploy.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

  notify:
    needs: [build, deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Send Email Report
        run: node sendreport.ts
        env:
          ENVIRONMENT: Staging
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          REPORT_DATE: ${{ needs.build.outputs.report_date }}
          TOTAL: ${{ needs.build.outputs.total }}
          PASSED: ${{ needs.build.outputs.passed }}
          FAILED: ${{ needs.build.outputs.failed }}
          SKIPPED: ${{ needs.build.outputs.skipped }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPORT_URL: ${{ needs.deploy.outputs.page_url }}staging-report-${{ needs.build.outputs.report_date }}/index.html
          URL_ADMIN: https://stg.chat.bluedropacademy.com/admin
          URL_CHATBOT: https://bluedropacademy.wixsite.com/website-1/chat6?rc=test-site
