name: Run Playwright Tests and Email Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
        node-version: 20

     - name: Install jq
       run: sudo apt-get update && sudo apt-get install -y jq

     - name: Install dependencies
       run: npm ci

     - name: Send Email Report via SendGrid API
       run: |
        node sendreport.ts
       env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        REPORT_DATE: 1
        TOTAL: 223
        PASSED: 44
        FAILED: 23
        SKIPPED: 33
        REPO_OWNER: 22
        REPO_NAME: 22244